name: Deploy with CSP Header

on:
  push:
    branches:
      - main # Adjust this to your default branch name

permissions:
  id-token: write
  contents: read
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      # Step 1: Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Set up environment variables for build
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
          REACT_APP_HOST: ${{ secrets.REACT_APP_HOST }}
        run: |
          run: |
          npm install
          npm run build

      # Step 3: Add a CSP header to the output
      - name: Add CSP Header
        run: |
            echo "Content-Security-Policy: \
            default-src 'self'; \
            script-src 'self'; \
            connect-src 'self' https://rag-time-production.up.railway.app; \
            img-src 'self'; \
            style-src 'self' 'unsafe-inline'; \
            font-src 'self'; \
            object-src 'none'; \
            frame-src 'none';" > ./build/_headers

      # Step 4: Deploy to GitHub Pages
      - name: Upload artifact for deployment
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./build

      - name: Deploy to Pages
        uses: actions/deploy-pages@v2
